project:
  type: website

website:
  title: "SMT201: GIS Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: overview.qmd
        text: Overview
      - href: proposal.qmd
        text: Proposal
      - href: methodology.qmd
        text: Methodology
      - href: findings.qmd
        text: Results and Discussion
      - text: "Webmaps"
        menu:
        - text: "Punggol Pre-school distribution"
          href: qgis2web/index.html
        - text: "Punggol 3D model"
          href: geoweb3D/index.html
    right:
      - about.qmd  
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


